### ISSUE TITLE
Security: Electron Framework

### ISSUE THREAD

**Issue by Echolon** [jitsi/jitsi-meet-electron#114]
Hello,

as CVE-2018-1000136 is already old, do you in general really think that Electron is the right thing use in terms of security of the app?

Kind regards, 
and however - awesome project!

https://twitter.com/jacobrossi/status/851992646151278592

https://www.trustwave.com/Resources/SpiderLabs-Blog/CVE-2018-1000136---Electron-nodeIntegration-Bypass/

**Comment by akshitkrnagpal** [comment]
Hey @Echolon 

 > CVE-2018-1000136

Yeah that was fixed. 
https://electronjs.org/blog/webview-fix

> and however - awesome project!

❤️ 



> do you in general really think that Electron is the right thing use in terms of security of the app?

Are you saying that Electron apps cannot provide security?

**Comment by saghul** [comment]
@Echolon I'm not sure what kind of answer you expect, so I'll try to give you a bit of background.

Jitsi Meet's primary targets are web and mobile, that's where pretty much all the development happens.

There are, however, things the web cannot do (see the always on top window, remote control) but a desktop app can. Here is where Electron enter the picture. If you look inside, you'll see that this application is a shell for the web app. Given this architecture, which we are not planning on changing, because it would be incredibly time consuming to write everything as a native desktop app, with virtually zero gains, we are left with frameworks such as Electron.

Out of those, Electron seems to have the most active community and features (last time I checked), plus the Node integration.

Yes, it has and will have bugs. A browser has a vast attack surface, add Node's to that and chances of bugs are high, that's a tradeoff we make.

We have the ability to perform silent auto-updates, so whenever Electron fixes a critical fix we can roll a new release to make sure our users get the best.

I'm happy to hear if you have any specific action items or suggestions.

Cheers,
