### ISSUE TITLE
Option to disable always on top window

### ISSUE THREAD

**Issue by patrickpichler** [jitsi/jitsi-meet-electron#171]
Hi,

is it possible to disable the always on top window? 
It is a bit annoying as it gets in my way most of the time.

**Comment by saghul** [comment]
There currently is no option for it. Adding one is not out of tyhe question, but I don't think we have the time now, patches are welcome though!

**Comment by saghul** [comment]
We just released a new version and the AoT window now has a X button so you can close it.

**Comment by casphas** [comment]
Just tested version 2.0.0 of the electron app on Linux (Debian 10, XMonad window manager). The button to close the AoT window works but the window pops up again as soon as the main window loses focus the next time.
An option to turn off the AoT window entirely would be greatly appreciated. Or a pointer to where this might be added and I can attempt a patch.

**Comment by aseeg** [comment]
I have the same problem when using the window manager i3wm: Switching to another workspace triggers the creation of the small window, which is stretched to cover the whole screen because of my standard settings and i3wm being a tiling window manager. I can then move the window onto another workspace/out of view, but as soon as I focus the main jitsi-meet-electron window, the small always-on-top-window vanishes, making it reappear as soon as I unfocus the main window (again stretched over my whole screen because of my i3wm standard settings).

I'd be happy about a way to disable the always-on-top window, or a way to stop it from disappearing when the main jitsi-meet-electron window gets the focus again.

Thank you for the hard work you put into Jitsi Meet and the Electron app.

**Comment by cocoonkid** [comment]
I'd also wish for a way to disable it. It is useless 99% of the time for me.

A setting to chose between them on the client and server both would be great.

**Comment by saghul** [comment]
Now that we have an advanced settings section, a PR adding a new setting there would be acceptable.

**Comment by casphas** [comment]
I believe this has been implemented with PR #264.

Thanks!
