### ISSUE TITLE
Possibility to install the application into Program Files

### ISSUE THREAD

**Issue by pechar** [jitsi/jitsi-meet-electron#310]
Hello, is there any way to install the application for all users in Program Files and not just in the user's profile? Run the installer with the /? does not display anything. I would very much welcome a solution based on the installation of the MSI package, or at least the analogy of the following MSI parameters and their integration into the EXE installer:

msiexec / i jitsi-meet.msi ALLUSERS=1 /qn

Thank you very much.

Regards,
Petr Charousek

**Comment by cmorty** [comment]
I would really appreciate this. I just built a chcolatey package (https://chocolatey.org/packages/jitsi-meet-electron/ - Yes the name is wrong, I hope to get that fixed soon). However Chocolaty is not designed to be a user-level package manger.

I did a bit of research, and as far as I can see the problem is with the one-click installer not allowing to set /allusers. A none-one-click config, as provided by Rocket Chat, would be highly appreciated.
https://github.com/RocketChat/Rocket.Chat.Electron/blob/5e85e48cbcba030cd71af29334728007bf89c8cf/electron-builder.json#L69-L75

Maybe provide two installers. The one-click and the advanced. :)

**Comment by saghul** [comment]
If we can make it work with the one click installer, great! But I’m not keen on adding more packages. Every little things adds up and we’re already spreading ourselves thin on this app.

**Comment by cmorty** [comment]
@saghul Nope. Being able to install globally will kill the one-click option. :( Everything else will require touching the electron-builder's NSIS install scripts.

**Comment by cmorty** [comment]
@pechar Finally found a solution: Download the One-Click-Installer. Unzip it (e.g. using 7z). You'll find two `.7z` files in the `$PLUGINSDIR`. You can just unpack them and start Jitsi-Meet. Or you can use my Chocolatey package: https://chocolatey.org/packages/jitsi-meet-electron/2.0.2 (I hope it goes through moderation soon. ;) )

**Comment by pechar** [comment]
@cmorty Thanks for the research, I'll try it :) Thanks for the research, I'll try it :) Hopefully it will soon be in the production version. ;)

**Comment by saghul** [comment]
We’ll just be providing the one-click installer for the foreseeable future. If Chocolatey repackages it and installs it to Program Files, great!

**Comment by cmorty** [comment]
It's through moderation: https://chocolatey.org/packages/jitsi-meet-electron
Unfortunately it seems like Chocolatey.org hast some issues when pushing packets, but 2.1.0 should be there soon. :)
