### ISSUE TITLE
not installer dialog is showing up with 2.0.2 and fresh Fedora 32

### ISSUE THREAD

**Issue by TimmiORG** [jitsi/jitsi-meet-electron#323]
Hi guys,
please note that no installer dialog is showing up when you tryp to run the first time a 2.0.2 on a fresh Fedora 32. I tried the same with the 1.1.1 and it worked. 
Best regards
Christoph

**Comment by saghul** [comment]
What installer dialog?

**Comment by TimmiORG** [comment]
I mean the installed dialog which put Jitsi-Meet into your install applications.
Don't have a screenshot for it at the moment.
But it is a kind of Yes/No dialoag if you run the appimage for the first time.

**Comment by Nokia808** [comment]
@saghul 
I think the author of this issue is talking about the dialog that ask user on 1st run: "Do you like to integrate Jitsi with your system" which mean: "do you like to integrate Jitsi with your DE so that a run icon for Jitsi will added to your application menu". 

Not all AppImages use it. For example: LibreOffice AppImage not using it. 

If AppImage not using it, then all needed by user is to create a run icon to AppImage, which is very easy thing that can be achieved by "menu editor" ....... In fact, it is better to me not include this dialog because from my experiment with Rambox AppImage that use it, when you delete AppImage you have to manually remove it's "run icon" that created by this dialog ......

**Comment by saghul** [comment]
Ah, i see. We never enabled that explicitly, I never knew where it came from, I assumed it was an AppImage thing.

Do you know if there is a way t configure this from package.json perhaps?

**Comment by Nokia808** [comment]
@saghul 
Unfortunately, I do not know how because I'm not programmer. I can not help with this .........

**Comment by xoan** [comment]
> Ah, i see. We never enabled that explicitly, I never knew where it came from, I assumed it was an AppImage thing.
> 
> Do you know if there is a way t configure this from package.json perhaps?

Indeed it is an electron-builder thing, but since update to `22.4.0` in 08d53c1, *desktop integration* is not supported.

https://www.electron.build/configuration/appimage

> **Desktop Integration**
> 
> Since electron-builder 21 desktop integration is not a part of produced AppImage file. [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) is the recommended way to integrate AppImages.

**Comment by saghul** [comment]
Thanks for the help @xoan ! I guess there is much we ca do then. Closing.
