### ISSUE TITLE
macOS screen-sharing transmits initial screenshot even without system permissions

### ISSUE THREAD

**Issue by luclu** [jitsi/jitsi-meet-electron#366]
macOS `10.15.4`
jitsi-meet-electron `2.1.1`
server `meet.jit.si`

When disabling screen-capture permissions with macOS's privacy settings activating screen-sharing will transmit a screenshot of the moment when the sharing was activated. This screenshot will be shown client-side until the sharing is stopped.

Also during the screen-sharing session the mouse movement is transmitted and shown client-side.

**Comment by saghul** [comment]
> When disabling screen-capture permissions with macOS's privacy settings activating screen-sharing will transmit a screenshot of the moment when the sharing was activated. This screenshot will be shown client-side until the sharing is stopped.

This might be a macOS bug or an Electron one, nothing we can really act on. AFAICT it shares a frame of the screen sharing picker with no other content visible, might be a safety measure instead of failing outright.

> Also during the screen-sharing session the mouse movement is transmitted and shown client-side.

Same as in a browser when sharing the screen. This is expected.

**Comment by luclu** [comment]
Although I don't have knowledge of the codebase and electrons limits I urge not to close this issue as this is a bug which might even pose a security issue.
Perhaps a bugreport upstream might be constructive, too.

**Comment by saghul** [comment]
I tested this. It's how macOS behaves to hide your real screen.

This was my screen, the one I started sharing:

<img width="1920" alt="Screenshot 2020-06-03 at 09 40 34" src="https://user-images.githubusercontent.com/317464/83609850-19c51f00-a57f-11ea-9843-518cedcbe0f5.png">

And this is what arrived on the other side:

![IMG_0928](https://user-images.githubusercontent.com/317464/83609885-22b5f080-a57f-11ea-9061-39db5f565826.PNG)

Notice how all icons are gone and so is any other window.

This is just how the platform behaves.

**Comment by luclu** [comment]
Thank you for clarifing, @saghul.
In this case, I guess, the issue - while still unexpected behaviour - can be closed from a security standpoint.

**Comment by matt-cylanda** [comment]
I'm having the exact issue, but on both my Mac and PC. Same behavior on both. If I try to share my desktop on either one, nothing is shared, and when I stop sharing, the last frozen image of me is broadcast. I notice this also happens if I do end-2-end encryption or even just turn my cameras on and off and back on again.

I installed using docker is there a step I'm missing?

**Comment by luclu** [comment]
@matt-cylanda be sure to forward your NAT/firewall-ports 10000/udp (and 4443/tcp) to your jvb-docker container.

**Comment by matt-cylanda** [comment]
Ports were forwarded when I started the server. I forgot to mention almost everything works perfectly via browser, I’m only having these issues in the jitsi electron app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by matt-cylanda** [comment]
@luclu I missed the last part of your comment. When I use meet.jit.si, the elctron app works fine. I know the issue is with self hosting... I just don't know what it is in the self hosting that's broken.

Another odd note. On Mac , f I log in to a room on my self hosted server and share my desktop before joining with another session. When I enter with another user, it shows the desktop share, but as soon as I stop sharing, everything kind of breaks again.
