### ISSUE TITLE
Screensharing preview with Pipewire broken

### ISSUE THREAD

**Issue by t2d** [jitsi/jitsi-meet-electron#608]
![123924502-52a21400-d98a-11eb-9842-e2162ed8723d](https://user-images.githubusercontent.com/1834580/124296217-00175200-db5a-11eb-81db-51977371c1d7.png)
![123924497-52097d80-d98a-11eb-94e2-e434034ca692](https://user-images.githubusercontent.com/1834580/124296224-00afe880-db5a-11eb-9f65-72f7d60bef88.png)

## Description

Follow up on #567
The preview is broken but clicking on "share"/"teilen" actually starts the pipewire sharing menu and everything works afterwards.

# Environment details
Fedora 34
Flatpak app version 2.8.7

**Comment by snaggen** [comment]
I see this with Flatpak 2.8.8 also (Fedora 34 Wayland session).

**Comment by vchernin** [comment]
This isn't an issue in Chromium which has a different looking preview. Presumably it's because Chromium's preview has been tweaked to use the data from PipeWire. Unfortunately Chromium still isn't a good example, as it has an issue where there are 2 PipeWire dialogs, so the preview Chromium gives isn't very helpful as it appears after the first dialogs. Note to test with Chromium you need to set [chrome://flags/#enable-webrtc-pipewire-capturer](chrome://flags/#enable-webrtc-pipewire-capturer) to enabled.

I wonder if the sanest solution is just to remove the screen sharing preview all together for wayland users, and just going right to the PipeWire prompt when a user presses the first share button.

**Comment by vchernin** [comment]
I made an issue report for Electron as this affects Element and Slack too: https://github.com/electron/electron/issues/30652

**Comment by saghul** [comment]
Closing since there is nothing actionable on our end. Once Electron is fixed we'll get the fix with an Electron bump.
