### ISSUE TITLE
Clear cache button for normal user

### ISSUE THREAD

**Issue by KRW85** [jitsi/jitsi-meet-electron#800]
Would it be possibble to add a "clear cache button" to the programm?
Normal endusers can´t find the folder (C:\Users\<user>\AppData\Roaming\<yourAppName>\Cache)  on there own.

**Comment by saghul** [comment]
Why would they need to do that?

**Comment by KRW85** [comment]
In my case we edited the all.css file and so the chat box vanished for all users.
So we undo the changes and we must go to every enduser to clear the cache, so they see the chatbox again.
I don´t know if something like this will happen again. Thats why i ask.

**Comment by csett86** [comment]
@KRW85 When editing or reverting the all.css (or on normal updates of your jitsi instance), always add a cache buster (dummy query param) in the index.html where the all.css is loaded.

The default packages do it like this with v=6447 and counting upwards:

    <link rel="stylesheet" href="css/all.css?v=6447">

You can do the same in your install. The only purpose of the v= something parameter is to force loading the css from the server instead of using cached values. With this you can fix these issues server side instead of asking all users to reload or push a hypothetical refresh button.

Thus I would close this here.
