### ISSUE TITLE
A bug when I am sharing my screen 

### ISSUE THREAD

**Issue by Dev-Code24** [jitsi/jitsi-meet-electron#823]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

## Description
---
This bug is visible when I am sharing my screen and then viewing, what I am sharing. It seems to be some kind of frame rate-related issue 
## Current behavior
---
According to me, the frame rate is dropping or there is some issue in the backend.
## Expected Behavior
---
There should be no drop in frame rates when I am sharing screen
## Steps to reproduce
---
I am sharing a video link in which you can see the way to reproduce the issue.

https://photos.app.goo.gl/DxypNzGjCpETp5uR7

# Environment details
---
macOS 13.0.1 , node 19.3.0

**Comment by saghul** [comment]
Not sure exactly what you mean by frame ripping here.

When you watch your own screen share, you see the local version, it doesn't go through the server.

In addition you'll experience the "infinity" effect of you are watching the same screen you share, this is normal, that's why we have a screen to avoid it.

**Comment by Dev-Code24** [comment]
The infinity effect is fine because I've seen it in other meeting software's like Google meet and zoom, and the reason you gave for the other thing also is making sense to me.
