### ISSUE TITLE
How to minimize and close jitsi-meet desktop application to system tray?

### ISSUE THREAD

**Issue by iamstonecutter** [jitsi/jitsi-meet-electron#970]
Would really like the option to close and minimize to system tray.

I use Debian and Arch, both on KDE, and this feature is really necessary for workflow. 

Too many times now I've accidentally closed Jitsi in a conference call by clicking X because I am so used to this feature being available in zoom and many other apps I use.

Please implement this.

**Comment by csett86** [comment]
I understand the requirement, but unfortunately the conference lives in the window, so if you close it, its gone (as you noticed).

As Jitsi Conferences require Web-RTC and other browser technology, we cant move it "somewhere else" so that the conference continues even without an electron window. So unfortunately I dont see a way how to implement that. Sorry!
